    export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
    export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
    export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";

    export const GET_PRODUCT_DETAILS_REQUEST = "GET_PRODUCT_DETAILS_REQUEST";
    export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";
    export const GET_PRODUCT_DETAILS_FAILURE = "GET_PRODUCT_DETAILS_FAILURE";
    
    export const GET_BRANDS_REQUEST = "GET_BRANDS_REQUEST";
    export const GET_BRANDS_SUCCESS = "GET_BRANDS_SUCCESS";
    export const GET_BRANDS_FAILURE = "GET_BRANDS_FAILURE";

